### ISSUE TITLE
ViewPropTypes will be removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types

### ISSUE THREAD

**Issue by PudinDeveloper** [PudinDeveloper/react-native-expo#1]
## Documentation about the issue
This solution to the issue was found in this [link of StackOverflow](https://stackoverflow.com/questions/71702392/viewproptypes-will-be-removed-from-react-native-migrate-to-viewproptypes-export)
The solution was mentioned by [CodingEra](https://stackoverflow.com/users/9920209/codingera)

### Solution
This is the patch issue and can be resolved by just replacing few lines of code:

1. check if you have installed deprecated-react-native-prop-types package if not run the below command first.
2.1. `yarn add deprecated-react-native-prop-types`
3. inside **_node_modules/react-native/index.js_**
4. replace these functions with the below lines

``` Javascript
// Deprecated Prop Types
get ColorPropType(): $FlowFixMe {
  console.warn('');
  return require('deprecated-react-native-prop-types').ColorPropType;
},

get EdgeInsetsPropType(): $FlowFixMe {
  console.warn('');
  return require('deprecated-react-native-prop-types').EdgeInsetsPropType;
},

get PointPropType(): $FlowFixMe {
  console.warn('');
  return require('deprecated-react-native-prop-types').PointPropType;
},

get ViewPropTypes(): $FlowFixMe {
  console.warn('');
  return require('deprecated-react-native-prop-types').ViewPropTypes;
},
```

**Comment by dagp-ucol** [comment]
@Brandon2002 this is the code solution for the issue in the project with [Expo](https://expo.dev/).
